# Generated by Django 4.2.5 on 2023-09-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomNote', '0002_rename_created_at_note_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='edited_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='textContent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
