# Generated by Django 4.2.5 on 2023-09-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomNote', '0003_label_name_alter_note_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='randomNote.note'),
        ),
    ]
