# Generated by Django 4.2.5 on 2023-10-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomNote', '0006_alter_label_name_listitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text_content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(default='', null=True),
        ),
    ]
